name: Deploy to Google Cloud Run - Production

on:
  push:
    branches:
      - master

jobs:
  lint-and-deploy:
    name: Lint and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 必要に応じてバージョンを変更

      # npm のキャッシュを使用して依存関係のインストールを高速化
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # Lint の実行
      - name: Run Lint
        run: npm run lint

      # Lint エラーがある場合はデプロイを停止
      - name: Check Lint Status
        if: failure()
        run: exit 1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }}

      - name: Deploy to Google Cloud Run - Production
        run: |
          gcloud run deploy pele-server-prod \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }} \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated
