name: Deploy to Google Cloud Run - Production

on:
  push:
    branches:
      - master

jobs:
  lint-and-deploy:
    name: Lint and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      -  run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Lint
        run: pnpm run lint

      - name: Check Lint Status
        if: failure()
        run: exit 1

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -f Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }}

      - name: Deploy to Google Cloud Run - Production
        run: |
          gcloud run deploy pele-server-prod \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pele-server:${{ github.sha }} \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated
